### PR TITLE
QuestionsStyling

### PR DESCRIPTION
**Pull request by kuzmabr**
See styles.css and new styling.

### CODE REVIEW

**Review by mindiweik — APPROVED** [review]
Looks good! Thanks for adding in the comments for future reference as well!

**Review by AaronSMiller — APPROVED** [review]
I like your style! Approved!

**Review by mindiweik — APPROVED** [review]
Reviewed and approved

**Comment by mindiweik** [comment]
[Client Change Request - Size: 2](https://trello.com/c/LX5S2ycJ/104-client-change-request-size-2)

**Review by thomascvan — APPROVED** [review]

**Pull request merged**
