### PR TITLE
basic server and helper-funcs

### PR DESCRIPTION
**Pull request by kuzmabr**
I believe I have officially rebased and pushed the server up.

### CODE REVIEW

**Review by mindiweik — APPROVED** [review]
Can we remove this from the QuestionsAPI/ProductsAPI files per our conversation with Leslie and instead use the token in the server?
> const TOKEN = process.env.API_TOKEN;

Otherwise all looks great! Approved :)

**Review by thomascvan — APPROVED** [review]
LGTM. We can refactor the API key into our server next time.

**Review by AaronSMiller — APPROVED** [review]
Based off my conversation with you and Mindi I believe this is our best course of action. We are now returning data in a manageable way and this will contribute to the overall sucess of the project

**Comment by mindiweik** [comment]
[Hide API Key from Request Headers - Size: 2](https://trello.com/c/KViRy4vK/56-hide-api-key-from-request-headers-size-2)

**Pull request merged**
