### PR TITLE
updates to package.json, product api, and overview module

### PR DESCRIPTION
**Pull request by mindiweik**
1. add script to watch jest files in package.json (in addition to "test" script for jest)
2. update product api doc and corresponding calls in index.jsx
3. update initial overview widget test suite for phase 1 requirements

*note that .env is not currently working as expected on my end and I was unable to get it working; api key was hard-coded into the file during testing (removed for committing and pull request) and it would be good to get this working

### CODE REVIEW

**Review by thomascvan — APPROVED** [review]
Reviewed all changes. LGTM.

**Review by kuzmabr — APPROVED** [review]
Thank you Mindi for the work!

**Review by AaronSMiller — APPROVED** [review]
Approved!

**Comment by mindiweik** [comment]
[API Docs - ProductAPI.js](https://trello.com/c/HjketyVv/34-api-docs-productapijs)

**Pull request merged**
