### PR TITLE
overview product basics

### PR DESCRIPTION
**Pull request by mindiweik**
- rebased from recent merges
- updated server functionality
- added updated functionality to index.jsx
- added props passing for overview files

### CODE REVIEW

**Review by kuzmabr — APPROVED** [review]
We worked on this collectively. Glad we now all have the same code base.

**Review by thomascvan — APPROVED** [review]

**Review by AaronSMiller — APPROVED** [review]
Approved- Worked on this communally, issues resolved with server!

**Comment by mindiweik** [comment]
[Overview - Product Overview - Size: 0/1](https://trello.com/c/2p2oqKB9/23-overview-product-overview-size-0-1)

**Comment by mindiweik** [comment]
[Overview - Product Category/Product Title - Size: 0](https://trello.com/c/kpqzcY7B/21-overview-product-category-product-title-size-0)

**Comment by mindiweik** [comment]
[Overview - Product Information - Size: 5](https://trello.com/c/UMvNyt8L/17-overview-product-information-size-5)

**Pull request merged**
