### PR TITLE
folder structures with test suite

### PR DESCRIPTION
**Pull request by kuzmabr**
First CoLLECTIVE pull and MErge@!@!@!E!##E!

### CODE REVIEW

**Comment by AaronSMiller** [comment]
ApPpRoVeD

**Comment by thomascvan** [comment]
Looks good. Approved.

**Comment by mindiweik** [comment]
aPpRoVeD

**Review by thomascvan — APPROVED** [review]
Approved.

**Review by AaronSMiller — APPROVED** [review]
request changes ASAP - SEV 1 OUTTAGE

**Review by mindiweik — APPROVED** [review]
aPPrOvEd - What more can I say?

**Pull request merged**
