### PR TITLE
Overview update css formatting

### PR DESCRIPTION
**Pull request by mindiweik**
- made several updates to the overview setup
- mainly added css to the components themselves

note: this overall format is mostly an experiment -- if it's too cluttered we can move it to its own CSS doc instead or I can move the CSS items to another React doc if this method works well, but needs to be decluttered

### CODE REVIEW

**Comment by mindiweik** [comment]
[Overview - General CSS for layout and functionality - Size: 3](https://trello.com/c/zsAulwWG/113-overview-general-css-for-layout-and-functionality-size-3)

**Review by kuzmabr — APPROVED** [review]
Well done moving the CSS into the react files.

**Comment by mindiweik** [comment]
[Overview - Default View - Size: 4](https://trello.com/c/fCAwGl2U/111-overview-default-view-size-4)

**Comment by mindiweik** [comment]
[Overview - Expanded View/Overlay - Size: 4](https://trello.com/c/dDBjM0d1/112-overview-expanded-view-overlay-size-4)

**Review by AaronSMiller — APPROVED** [review]
Looking good! Loving the icons cant wait to see them merged in!

**Review by thomascvan — APPROVED** [review]

**Pull request merged**
