### PR TITLE
Overview Cart (Subcomponent 3 - initial setup)

### PR DESCRIPTION
**Pull request by mindiweik**
- made changes to my file structures
- added drop-downs for selecting the size and quantity
- added the initial button for the cart
- added stars to the stars and reviews section

- dealt with multiple rebase updates while building so hopefully all files are up-to-date!
- made minor updates to Brian's files we discussed

### CODE REVIEW

**Comment by mindiweik** [comment]
[Overview - Size Dropdowns - Size: 2](https://trello.com/c/t1eIlaOX/59-overview-size-dropdowns-size-2)

**Comment by mindiweik** [comment]
[Overview - Quantity Dropdowns - Size: 2](https://trello.com/c/yEGrxToy/27-overview-quantity-dropdowns-size-2)

**Review by thomascvan — APPROVED** [review]
Approved!

**Comment by mindiweik** [comment]
[Overview - Add to Cart Functionality - Size: 3](https://trello.com/c/CiwA7kzr/28-overview-add-to-cart-functionality-size-3)

**Comment by mindiweik** [comment]
[Overview - Add to Cart - Size: 5](https://trello.com/c/hDrGxMpH/19-overview-add-to-cart-size-5)

**Review by AaronSMiller — APPROVED** [review]
Approved, welcome to the fun css land lol

**Pull request merged**
