### PR TITLE
Modals photos2

### PR DESCRIPTION
**Pull request by kuzmabr**
This is my basic functionality. I am hoping I rebased well. I am worried about merge conflicts.

### CODE REVIEW

**Review by AaronSMiller — APPROVED** [review]
Looks good! Thank you for removing the CSS of yours I accidentally added back in! Approved!

**Review by mindiweik — COMMENTED** [review]
@kuzmabr - Can you please remove your coverage files and recommit? I added this in the .gitignore in a previous merge, but it's possible yours were committed before that was in place.

**Review by thomascvan — CHANGES_REQUESTED** [review]
Please add coverage to gitignore.  all else looks good.

**Review by mindiweik — APPROVED** [review]
Approved, thanks!

**Pull request closed without merging**
