### PR TITLE
Dotenv added to server

### PR DESCRIPTION
**Pull request by thomascvan**

### CODE REVIEW

**Review by kuzmabr — APPROVED** [review]
Thank you for the fix.

**Review by mindiweik — APPROVED** [review]
Looks good! Thanks for making that change so quickly!

**Review by AaronSMiller — APPROVED** [review]
Updated dependencies in support for server, looks good for hiding token. Approved.

**Comment by mindiweik** [comment]
[Hide API Key from Request Headers - Size: 2](https://trello.com/c/KViRy4vK/56-hide-api-key-from-request-headers-size-2)

**Pull request merged**
