### PR TITLE
Overview Views (Subcomponent 4 - initial setup)

### PR DESCRIPTION
**Pull request by mindiweik**
- ensure images render properly for the default view
- ensure thumbnails render for default view
- toggle between images setup
- toggle between default view and expanded view (need to add an overlay)
- update unit tests to account for updated content and props

**Additional:**
- update toggleStar for the outfit toggle (note this @AaronSMiller - open to updates as needed!)
- note that I made some minor updates on my end to the reviews files per Thomas' recent PR to avoid errors while developing this portion -- double-check this for accuracy

### CODE REVIEW

**Comment by mindiweik** [comment]
[Overview - Image Gallery - Size: 5](https://trello.com/c/IE5XDOue/16-overview-image-gallery-size-5)

**Comment by mindiweik** [comment]
[Overview - Default Gallery View - Size: 4](https://trello.com/c/NsHscNWg/29-overview-default-gallery-view-size-4)

**Comment by mindiweik** [comment]
[Overview - Expanded Gallery View - Size: 4](https://trello.com/c/B6vgDVr7/30-overview-expanded-gallery-view-size-4)

**Review by thomascvan — APPROVED** [review]
My changes look like it made it through to yours.  If any issues come up, I can address on my PR.

**Review by kuzmabr — APPROVED** [review]
Great job Testing ;) Trusting everyone else.

**Pull request merged**
