### PR TITLE
bug fix.  updated and corrected dependencies.

### PR DESCRIPTION
**Pull request by thomascvan**
Updated and corrected dependencies for React 17.  Added dotenv-webpack and removed dotenv. Modified webpack.config to properly support webpack + react.  Changes confirmed working.

### CODE REVIEW

**Comment by thomascvan** [comment]
[Bug Ticket - dependency issues](https://trello.com/c/dVvH6p60/40-bug-ticket-dependency-issues)

**Comment by thomascvan** [comment]
[Bug Ticket - dotenv not working](https://trello.com/c/1PGCmqeo/39-bug-ticket-dotenv-not-working)

**Review by kuzmabr — APPROVED** [review]
Thank you for fixing the DotEnv issue Thomas!

**Review by AaronSMiller — APPROVED** [review]
Approved!

**Review by mindiweik — APPROVED** [review]
Looks good! Thanks Thomas! apPROVEd

**Review by thomascvan — COMMENTED** [review]
Approved

**Comment by thomascvan** [comment]
[Spike Task - How to resolve merge requests that can't be resolved in browser](https://trello.com/c/g0TyzakP/55-spike-task-how-to-resolve-merge-requests-that-cant-be-resolved-in-browser)

**Pull request merged**
