### PR TITLE
Product Overview basics (Subcomponent 1)

### PR DESCRIPTION
**Pull request by mindiweik**
- added props to be passed down from the index.jsx to overview to subcomponents
- confirmed initial render of these subcomponents
- reorganized file structure for future structure design
- added initial unit tests only

### CODE REVIEW

**Review by thomascvan — APPROVED** [review]

**Comment by mindiweik** [comment]
[Overview - Product Overview - Size: 0/1](https://trello.com/c/2p2oqKB9/23-overview-product-overview-size-0-1)

**Comment by mindiweik** [comment]
[Overview - Product Category/Product Title - Size: 0](https://trello.com/c/kpqzcY7B/21-overview-product-category-product-title-size-0)

**Comment by mindiweik** [comment]
[Overview - Stars (# Reviews) - Size: 3](https://trello.com/c/CPkTQSVS/20-overview-stars-reviews-size-3)

**Comment by mindiweik** [comment]
[Overview - Toggle Outfit Star - Size: 2](https://trello.com/c/VvUAJbUS/24-overview-toggle-outfit-star-size-2)

**Comment by mindiweik** [comment]
[Overview - Product Information - Size: 5](https://trello.com/c/UMvNyt8L/17-overview-product-information-size-5)

**Comment by mindiweik** [comment]
[Overview - Price [from Style] - Size: 2](https://trello.com/c/v5VC5Zgz/22-overview-price-from-style-size-2)

**Review by kuzmabr — APPROVED** [review]
Thank you for leading the way on testing suites.

**Review by AaronSMiller — APPROVED** [review]
Looks good to me! - Approved

**Pull request merged**
